### ISSUE TITLE
'defineProperty' is null or not an object

### ISSUE THREAD

**Issue by 11111000000** [WebReflection/ie8#16]
shown in IE 8.0.6001.19587
on this:

---
defineProperty = Object.defineProperty ||
	    // just in case ...
	    function (object, property, descriptor) {
	      object[property] = descriptor.value;
	    },

---

I can't understand...

**Comment by WebReflection** [comment]
? code, examples, where, what?

**Comment by flcdrg** [comment]
I'm seeing the same problem. 
MDN indicates that [support in IE8 is for defineProperty is for DOM objects only](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/Object/defineProperty).

Repro by including jspm_packages/github/webreflection/ie8@0.2.4/build/ie8.max.js

Then note in IE Debugger the error   "Object doesn't support this property or method  ie8.max.js, line 322 character 11"

Which corresponds to this:

temple =  self[SECRET] ||
                      defineProperty(
                        self, SECRET, {value: {}}
                      )[SECRET],

**Comment by WebReflection** [comment]
I know that, and indeed it's used only on host objects. Can I have an example page to verify?

Is that XHR thing? Thanks

**Comment by WebReflection** [comment]
unless proven this is not caused by third part scripts and I can verify ... nothing to do here. Feel free to reopen if you have an example. Thanks
