### ISSUE TITLE
CDN-Link retursn 404

### ISSUE THREAD

**Issue by stefan-niedermann** [WebReflection/ie8#17]
please adjust your README.

**Comment by WebReflection** [comment]
once the PR will be accepted, the CDN version should align with this repo.

Apologies for any inconvenience, feel free to use `0.2.3` instead of `0.2.5` if necessary, or grub the latest [build/ie8.js](build/ie8.js) file.

**Comment by WebReflection** [comment]
it's now available as expected via CDN
