### ISSUE TITLE
Do you know how to use this polyfill with babel browser polyfill?

### ISSUE THREAD

**Issue by vdzundza** [WebReflection/ie8#21]
I've an error with getters/setters. I investigated that babel polyfill check whether get/set methods are in attributes and throws exception.

**Comment by WebReflection** [comment]
babel is not compatible with IE8 ... how can I help?

**Comment by WebReflection** [comment]
written  IE9+ ... surely you might have some IE8 compatibility but you won't go far with getters and setters.

It's all written  in  there https://babeljs.io/docs/faq/#what-is-the-browser-compatibility-
