### ISSUE TITLE
HTMLSelectElement defineProperties  throw error in IE8

### ISSUE THREAD

**Issue by acelan86** [WebReflection/ie8#23]
```javascript
defineProperties(HTMLSelectElement, {
    value: {
      get: function () {
        return this.options[this.selectedIndex].value;
      }
    }
  });
```
throw error in IE8

it must be?
```javascript
defineProperties(window.HTMLSelectElement.prototype, {
    value: {
      get: function () {
        return this.options[this.selectedIndex].value;
      }
    }
  });
```

**Comment by WebReflection** [comment]
I've removed the block since it's apparently not needed in IE8 and [the test](http://webreflection.github.io/ie8/test/) in IE8 passes anyway.

Cheers

**Comment by AprilArcus** [comment]
Thanks for resolving this! Are you able to publish a new version to npm? I've pointed my package.json at `WebReflection/ie8#693fe7c568c78dfa0bac4790b697b879901e53be` in the meantime.

**Comment by WebReflection** [comment]
Apologies I forgot about it, `0.2.10` has been published right now.
