### ISSUE TITLE
Publish ie8.max.js

### ISSUE THREAD

**Issue by neersighted** [WebReflection/ie8#25]
I think it would be better to specific the 'max' build as `main`, as it makes debugging much easier, and anyone who uses the file via commonjs/npm likely will minify it as part of their own build.

**Comment by WebReflection** [comment]
could you please define "much easier" and what kind of problem would that solve?

**Comment by neersighted** [comment]
It is easier to debug when you have a full callstack of unminified functions, and you can view the original source. Even with sourcemaps, they are useless if the original input file into your bundle was minified.

**Comment by WebReflection** [comment]
For the npm repository I actually agree, the min version should have been CDN specific. Will change that soon.

**Comment by WebReflection** [comment]
since this might be a breaking change for someone, I've tagged the latest `0.3.0` and it publishes the `.max` version.
