### ISSUE TITLE
some new ie8 Compatibility

### ISSUE THREAD

**Issue by alwaysYoungCohen** [WebReflection/ie8#30]
ie8 is not support indexOf and compareDocumentPosition function

**Comment by ljharb** [comment]
@alwaysYoungCohen for `Array#indexOf`, you should be using https://github.com/es-shims/es5-shim

**Comment by WebReflection** [comment]
Yes, this poly won't add ES5 or ES6 features so use @ljharb polyfill for that.

I'll keep this open to see how difficult this spec could be to be implemented in here:
https://www.w3.org/TR/DOM-Level-3-Core/core.html#Node3-compareDocumentPosition

**Comment by alwaysYoungCohen** [comment]
thanks@ljharb@WebReflection
