### ISSUE TITLE
Add changelog?

### ISSUE THREAD

**Issue by lencioni** [WebReflection/ie8#34]
I'm trying to evaluate what I need to be on the lookout for when updating. It would be really helpful to have a changelog to reference.

**Comment by WebReflection** [comment]
I'm not planning to waste too much time on this project but I'll try to make comments more explicit, hope this works.
https://github.com/WebReflection/ie8/commits/master

What I can say is that rarely there are fixes to what's there already, sometimes there are little features added like `pageX` and `pageY`.
