### ISSUE TITLE
Some fixes of event and window attributes

### ISSUE THREAD

**Issue by joonis** [WebReflection/ie8#36]
Attached a patch to normalize some event and window attributes.

Window: pageXOffset, pageYOffset, scrollX, scrollY, innerWidth, innerHeight
Event: which, charCode, buttons, button (as far as practicable)

[ie8.patch.txt](https://github.com/WebReflection/ie8/files/756131/ie8.patch.txt)

**Comment by ljharb** [comment]
Patch files aren't very easy to review - you may want to send a pull request instead?
